edition = "2021"
wrap_comments = true
tab_spaces = 2
reorder_imports = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_strings = true

# error_on_line_overflow = true
# unstable_features = true
# format_doc_comments = true
# normalize_doc_attributes = true
# normalize_comments = true
